### ISSUE TITLE
Cycle detected

### ISSUE THREAD

**Issue by zakwillis** [PiranhaCMS/piranha.core.basicweb#11]
Hi, getting the error below.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  Piranha -> Piranha (>= 5.3.1).	Piranha	C:\...\Web\Piranha\Piranha.csproj	1

**Comment by tidyui** [comment]
Hi there! You can't create a project with the same name as a package reference!

**Comment by zakwillis** [comment]
Don't tell me i did something as stupid as this 😁? Will test later thanks.
