### ISSUE TITLE
Header Block different sizes on Start page vs Blog page

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core.basicweb#4]
![heading-height-issue](https://user-images.githubusercontent.com/740215/43930786-c3c11fc4-9c7e-11e8-856a-2a2008105e56.png)

![heading-height-issue2](https://user-images.githubusercontent.com/740215/43930837-00c222f6-9c7f-11e8-8563-5fd081de4a80.png)

See above..

**Comment by tidyui** [comment]
This is by design. The header expands to the amount of content that is added. Also, it is just a template that is supposed to be used as a blueprint and modified in the project!

Regards

**Comment by CastleSoft** [comment]
Thanks.. If I extend this page (like my HideTitle).
What Div / Class / ID do you recommend I hook my max size against ? (so I don't clash with future design updates etc).  I'm thinking of a 'Fix Header Size' tick box and a Size.

**Comment by tidyui** [comment]
The project templates are just like any other project template. When the project has been created there is no connection to the template and the created files will never be updated. Only content that are include into your project as a NuGet **package reference** can be updated.

So the templates are really just to be considered as a blueprint, an example of how you could write your web application to get you started quickly.

With that said, you can update the provided `.cshtml` files any way you want!

Regards
