### ISSUE TITLE
Package as a `.nupkg`

### ISSUE THREAD

**Issue by dougajmcdonald** [PiranhaCMS/piranha.core.basicweb#5]
I have a situation where I cannot install the template from the command line due to proxy issues. 

Could you possibly release the template repo as a `.nupkg` file as this article suggests I should be able to install it from a file locally.

https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#to-install-a-template-from-a-local-nupkg-file

**Comment by tidyui** [comment]
Hi there! You can download the package from NuGet by clicking `Download package` on the following page!

https://www.nuget.org/packages/Piranha.BasicWeb.CSharp/

Best regards!
