### ISSUE TITLE
Quote content issues

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core.basicweb#7]
A couple of minor issues with 5.2 quote content.

1) Designer shows vertical bar

![quote-css](https://user-images.githubusercontent.com/740215/46982946-28e92600-d12a-11e8-8520-77a2043fad53.png)

Preview/Live does not show vertical bar

![quote-css2](https://user-images.githubusercontent.com/740215/46982953-2be41680-d12a-11e8-8a5f-bf8de86f80bc.png)

2) Spaces in quote appear as &nbsp;

![quote-blank-spaces](https://user-images.githubusercontent.com/740215/46983086-a745c800-d12a-11e8-8b16-dd8c3126ee7b.png)

![quote-black-spaces2](https://user-images.githubusercontent.com/740215/46983089-aca31280-d12a-11e8-9b4d-2cc7d6133178.png)

**Comment by tidyui** [comment]
Hi there!

Your **first issue** is not really a bug as there's no connection between how content is rendered in the web application and in the manager, but I'll add a border to the application styling for clarity.
