### ISSUE TITLE
TextField issue

### ISSUE THREAD

**Issue by CastleSoft** [PiranhaCMS/piranha.core.basicweb#8]
When adding a TextField as shown:

![textfield](https://user-images.githubusercontent.com/740215/46983172-16232100-d12b-11e8-8387-743b87620a9c.png)

The field name is added, not the content (see below):

![textfield2](https://user-images.githubusercontent.com/740215/46983175-1a4f3e80-d12b-11e8-9cdb-612f0a542de1.png)

**Comment by tidyui** [comment]
See #6
